oskardudycz/EventSourcing.NetCore

CQRS.Tests/Commands/Commands.cs, CQRS.Tests/Queries/Queries.cs, Domain/Commands/CommandBus.cs, Domain/Commands/IAsyncCommandHandler.cs, Domain/Commands/ICommandHandler.cs, Domain/Queries/IAsyncQueryHandler.cs, Domain/Queries/IQuery.cs, Domain/Queries/IQueryHandler.cs, Domain/Queries/QueryBus.cs, MediatR.Tests/Publishing/AsynchronousHandler.cs, MediatR.Tests/Publishing/MoreThanOneHandler.cs, MediatR.Tests/Publishing/SynchronousHandler.cs, MediatR.Tests/Sending/AsynchronousHandler.cs, MediatR.Tests/Sending/MoreThanOneHandler.cs, MediatR.Tests/Sending/SynchronousHandler.cs, Sample/EventSourcing.Sample.Transactions/Domain/Accounts/Account.cs, Sample/EventSourcing.Sample.Transactions/Views/Accounts/Handlers/GetAccountsHandler.cs
Really small changes,. mostly about readability. For example, during presentation sometimes it was hard to see whats the T type and where it goes.
=> Readonly, in/out in interefaces, some readability improvements

Sample/EventSourcing.Sample.Transactions/Contracts/Accounts/Queries/GetAccount.cs, Sample/EventSourcing.Sample.Transactions/Contracts/Accounts/Queries/GetAccounts.cs, Sample/EventSourcing.Sample.Transactions/Domain/Accounts/Account.cs, Sample/EventSourcing.Sample.Transactions/Domain/Accounts/Handlers/ProcessInflowHandler.cs, Sample/EventSourcing.Sample.Transactions/Views/Accounts/AccountSummary/AccountSummaryView.cs, Sample/EventSourcing.Sample.Transactions/Views/Accounts/AccountSummary/AccountSummaryViewProjection.cs, Sample/EventSourcing.Sample.Transactions/Views/Accounts/AllAccountsSummary/AllAccountsSummaryView.cs, Sample/EventSourcing.Sample.Transactions/Views/Accounts/AllAccountsSummary/AllAccountsSummaryViewProjection.cs, Sample/EventSourcing.Sample.Transactions/Views/Accounts/Handlers/GetAccountHandler.cs, Sample/EventSourcing.Sample.Web/Controllers/AccountsController.cs, Sample/EventSourcing.Sample.Web/Controllers/ClientsController.cs, Sample/EventSourcing.Sample.Web/Controllers/TransactionController.cs, Sample/EventSourcing.Sample.Web/Controllers/TransactionsController.cs, Sample/EventSourcing.Sample.Web/Startup.cs
Hello,
please review my changes before merge. 
I am new in ES and Marten, so I am not sure if everything is ok.
**ProcessInflowHandler** after my changes throws exception, with message:
> An item with the same key has already been added. Key {000000-0000-0000.....}.
This issue is somehow linked with **AccountSummaryView**, ClientId = Guid.Empty (000000-0000-0000.....) inside that view projection. I don't know how to fix it.
Best Regards
=> Add transaction controller and some improvements to account events

README.md
One is link to a post collecting a couple of articles I wrote to collect 5+ years of building a distributed Event Sourced system. The other is a light-weight projection library I've extracted from that same code-base.
=> Added additional resources that can help understand and build Event Sourcing

CQRS.Tests/Queries/Queries.cs, MediatR.Tests/Sending/SingleHandler.cs, Sample/BankAccounts/EventSourcing.Sample.Clients/Domain/Clients/Handlers/ClientsCommandHandler.cs, Workshop/02-EventSourcingAdvanced/MeetingsManagement/Storage/MartenRepository.cs, Workshop/02-EventSourcingAdvanced/MeetingsSearch/Meetings/MeetingQueryHandler.cs, Workshop/02-EventSourcingAdvanced/MeetingsSearch/Storage/ElasticSearchRepository.cs
The PR brings usage of the cancellation token when it's available. 
PS, remember that token with Task.Run can cancel the task only if it was not started.
=> Using ct when available

EventSourcing.NET.Presentation.sln
References in the presentation project weren't linked to the appropriate projects.
I adjusted the solution to reference the correct path.
=> Adjust the Presentation solution to reference the projects moved to root

README.md
Fixed the issue with the link to What if I told you that Relational Databases are in fact Event Stores? for the correct one that track the origin of the request.
=> Fixing the broken link

README.md
=> Fix the URL of article "Events should be as small as possible, right?"

Sample/ECommerce/README.md
Updated login information to match `docker-compose.yml` file.
Fixes #58
=> Update PG Admin login in README.md

Core/Config.cs, Core/Events/EventBus.cs, Sample/EventStoreDB/Simple/ECommerce.sln
- Fixed Wrong DI registration of EventBus and Tracing related factories.
- Added missing projects in Simple EventStoreDD sample solution
@cjjohansen, thank you for catching that up!
=> Fixed Wrong DI registration of EventBus and Tracing related factories.

Core.Kafka.Tests/Core.Kafka.Tests.csproj, Core.Kafka.Tests/KafkaProducerTests.cs, Core.Kafka/Consumers/KafkaConsumer.cs, Core.Kafka/Producers/KafkaProducer.cs, Core.Marten/Subscriptions/MartenEventPublisher.cs, EventSourcing.NetCore.sln, Sample/ECommerce/README.md, Sample/ECommerce/docker/docker-compose.yml, Sample/MeetingsManagement/Readme.md, Sample/MeetingsManagement/docker/docker-compose.yml, docker-compose.yml
- Fixed Kafka producer and consumer to correctly serialize/deserialize send Event with event envelope
- Upgraded Kafka images to latest 7.0.1 version
- Added a basic test for Kafka Producer
- Switched Kafka UI from `landoop/kafka-topics-ui` to `landoop/kafka-ui`
=> Fixed Kafka integration to correctly publish and get messages

Workshops/IntroductionToEventSourcing/07-BusinessLogic/Immutable/BusinessLogicTests.cs, Workshops/IntroductionToEventSourcing/08-BusinessLogic.Marten/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/09-BusinessLogic.EventStoreDB/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/10-OptimisticConcurrency.Marten/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/11-OptimisticConcurrency.EventStoreDB/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/Solved.sln, Workshops/IntroductionToEventSourcing/Solved/02-GettingStateFromEvents/Immutable/Solution1/GettingStateFromEventsTests.cs, Workshops/IntroductionToEventSourcing/Solved/02-GettingStateFromEvents/Immutable/Solution2/GettingStateFromEventsTests.cs, Workshops/IntroductionToEventSourcing/Solved/05-GettingStateFromEvents.Marten/Immutable/GettingStateFromEventsTests.cs, Workshops/IntroductionToEventSourcing/Solved/06-GettingStateFromEvents.EventStoreDB/Immutable/GettingStateFromEventsTests.cs, Workshops/IntroductionToEventSourcing/Solved/07-BusinessLogic/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/Solved/08-BusinessLogic.Marten/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/Solved/09-BusinessLogic.EventStoreDB/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/Solved/10-OptimisticConcurrency.Marten/Immutable/BusinessLogic.cs, Workshops/IntroductionToEventSourcing/Solved/11-OptimisticConcurrency.EventStoreDB/Immutable/BusinessLogic.cs
- Used `Concat` instead of wrong `Union` in "Introduction to Event Sourcing" workshop state aggregation
- Added proper solved exercises instead of Unsolved
=> Small fixes to Introduction to Event Sourcing workshop

Sample/ECommerce/Carts/Carts.Api/Program.cs
Updated Title from "Tickets" to "Carts"
=> Correct Typo In Open API Info Title

README.md
GoldenEye DDD was merged into core in https://github.com/oskardudycz/GoldenEye/commit/0f21d485816907c777f6f72887b45d125078e4cb
Template project was removed in https://github.com/oskardudycz/GoldenEye/commit/f0c9f99d73f788b359f53e7b73505b7f04812cb1
=> Update GoldenEye Links in README

Marten.Integration.Tests/CompositeIds/README.md, README.md
=> Fixed typo in the composite key example.

.github/workflows/build.dotnet.yml, Core.EventStoreDB/Subscriptions/EventStoreDBSubscriptionToAll.cs, Core.Marten/MartenConfig.cs, Core/Core.csproj, Sample/Helpdesk/Helpdesk.Api/Program.cs, Sample/HotelManagement/HotelManagement.Tests/Sagas/GroupCheckouts/GroupCheckoutTests.RecordGuestCheckoutFailure.cs, Sample/MeetingsManagement/MeetingsSearch.IntegrationTests/Meetings/CreatingMeeting/CreateMeetingTests.cs, Workshops/IntroductionToEventSourcing/03-AppendingEvents.Marten/AppendingEvents.cs, Workshops/IntroductionToEventSourcing/05-GettingStateFromEvents.Marten/Tools/MartenTest.cs, Workshops/IntroductionToEventSourcing/08-BusinessLogic.Marten/Tools/MartenTest.cs, Workshops/IntroductionToEventSourcing/10-OptimisticConcurrency.Marten/Tools/MartenTest.cs, Workshops/IntroductionToEventSourcing/Solved/03-AppendingEvents.Marten/AppendingEvents.cs, Workshops/IntroductionToEventSourcing/Solved/05-GettingStateFromEvents.Marten/Tools/MartenTest.cs, Workshops/IntroductionToEventSourcing/Solved/08-BusinessLogic.Marten/Tools/MartenTest.cs, Workshops/IntroductionToEventSourcing/Solved/10-OptimisticConcurrency.Marten/Tools/MartenTest.cs
Updated also GH actions versions.
=> Improved tests isolation for failing Marten-related tests

.github/workflows/build.docker.helpdesk.yml, .gitignore, Core.EventStoreDB.Tests/Core.EventStoreDB.Tests.csproj, Sample/Helpdesk/Helpdesk.Api.Tests/Settings.cs, Sample/Helpdesk/Helpdesk.Api/.dockerignore, Sample/Helpdesk/Helpdesk.Api/Dockerfile, Sample/Helpdesk/Helpdesk.Api/Helpdesk.Api.csproj, Sample/Helpdesk/Helpdesk.Api/Program.cs, Sample/Helpdesk/Helpdesk.Api/appsettings.Production.json
- Set up code generation for the Helpdesk example
- Added Marten Dockerfile to build an example
- Added build docker action for helpdesk sample
=> Added Marten Docker configuration example

Sample/EventsVersioning/ECommerce.V1/ECommerce.V1.csproj, Sample/EventsVersioning/ECommerce.V1/PublicAPI.Shipped.txt
It's a follow-up to the previous PR https://github.com/oskardudycz/EventSourcing.NetCore/pull/255 thanks to the suggestion from @danielmarbach :+1:
Read more: https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md
=> Added example of catching breaking changes to the package with Microsoft.CodeAnalysis.PublicApiAnalyzers

README.md
=> Fix to GoldenEye URL

Sample/ECommerce.Equinox/ECommerce.Domain/ECommerce.Domain.fsproj, Sample/ECommerce.Equinox/ECommerce.Domain/ExactlyOnceIngester.fs, Sample/ECommerce.Equinox/ECommerce.Infrastructure/Args.fs, Sample/ECommerce.Equinox/ECommerce.Infrastructure/ECommerce.Infrastructure.fsproj
- update to latest release Equinox/Propulsion packages
=> chore(Deps): Update to latest Equinox nugets

Core.Testing/TestWebApplicationFactory.cs, Sample/ECommerce/Carts/Carts.Api.Tests/ApiTest.cs, Sample/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/AddingProduct/AddProductTests.cs, Sample/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/Canceling/CancelShoppingCartTests.cs, Sample/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/Confirming/ConfirmShoppingCartTests.cs, Sample/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/Opening/OpenShoppingCartTests.cs, Sample/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/RemovingProduct/RemoveProductTests.cs, Sample/ECommerce/Carts/Carts.Api/Controllers/ShoppingCartsController.cs, Sample/ECommerce/Carts/Carts/Config.cs, Sample/ECommerce/Carts/Carts/ShoppingCarts/GettingCartById/GetCartById.cs, Sample/EventStoreDB/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/AddingProduct/AddProductTests.cs, Sample/EventStoreDB/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/Canceling/CancelShoppingCartTests.cs, Sample/EventStoreDB/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/Confirming/ConfirmShoppingCartTests.cs, Sample/EventStoreDB/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/RemovingProduct/RemoveProductTests.cs, Sample/EventStoreDB/Simple/ECommerce.Api.Tests/ShoppingCarts/AddingProduct/AddProductTests.cs, Sample/EventStoreDB/Simple/ECommerce.Api.Tests/ShoppingCarts/Canceling/CancelShoppingCartTests.cs, Sample/EventStoreDB/Simple/ECommerce.Api.Tests/ShoppingCarts/Confirming/ConfirmShoppingCartTests.cs, Sample/EventStoreDB/Simple/ECommerce.Api.Tests/ShoppingCarts/Opening/OpenShoppingCartTests.cs, Sample/EventStoreDB/Simple/ECommerce.Api.Tests/ShoppingCarts/RemovingProduct/RemoveProductTests.cs
Removed redundant retries from ESDB api tests, as we have already long polling in place
=> Added test collection for Marten ECommerce sample

Sample/Helpdesk/Helpdesk.Api/.dockerignore, Sample/Helpdesk/Helpdesk.Api/Dockerfile, Sample/Helpdesk/Helpdesk.Api/Incidents/GetCustomerIncidentsSummary/IncidentSummary.cs, Sample/Helpdesk/Helpdesk.Api/Program.cs, Sample/Helpdesk/Helpdesk.Api/docker-compose.yml, Sample/Helpdesk/Helpdesk.Api/nginx.conf
=> Added Nginx configuration with multiple replicas for Helpdesk sample

Core.Scheduling/PassageOfTimeJob.cs, Core.Scheduling/QuartzExtensions.cs, Core/Events/TimeHasPassed.cs, Sample/ECommerce/Orders/Orders/Orders/CancellingOrder/CancelOrder.cs, Sample/ECommerce/Orders/Orders/Orders/Config.cs
Read more in: https://event-driven.io/en/to_do_list_and_passage_of_time_patterns_combined/
=> Adjusted PassageOfTime example extending by the granular time events
