oskardudycz/EventSourcing.NetCore

DOCKERFILE
Upgrade DOCKERFILE .NET Core SDK container to .NET Core 2.2
=> Fix invalid .NET Core SDK used in Dockerfile

Workshop/01-EventStoreBasics/07-AggregateAndRepository/EventStore.cs
07-AggregateAndRepository/EventStore.cs has a bug in the EventStore::CreateAppendEventFunction where the creation of the postgres function uses the wrong type. It uses text but is should instead use jsonb.
=> Fix bug using incorrect type in append_event

README.md
Removed not needed 'only' in Message Bus section
"only all" -> "all"
=> Removed not needed 'only' in Message Bus section

README.md
Fix link that points to wrong article.
=> Fix link to: "Events should be as small as possible, right?"

.github/workflows/build.dotnet.testreport.yml, .github/workflows/build.dotnet.yml
Tests were failing on pull requests from forked repositories.  This appears to stem from the way GitHub handles workflows triggered by pull requests.
A note on the [dorny/test-reporter](https://github.com/dorny/test-reporter) says
> Workflows triggered by pull requests from forked repositories are executed with read-only token and therefore can't create check runs. To workaround this security restriction, it's required to use two separate workflows.
Changes were made based on the author's [Recommended setup for public repositories](https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories)
Fixes #63
=> Split build.dotnet.yaml into two workflows

Sample/ECommerce/Shipments/Shipments.Api/Startup.cs, Sample/ECommerce/Shipments/Shipments/Config.cs
During startup, ApplicationServices was not able to resolve the reference to ShipmentsDbContext. Using IApplicationBuilder and creating a new scope from app.ApplicationServices seems to have to addressed the issue.
Fixes #60
=> Convert ConfigureShipmentsModule to use IApplicationBuilder.

Sample/ECommerce/Shipments/Shipments/Packages/PackageService.cs
Two Shipment.Api tests, CreateCommand_ShouldCreate_Package and CreateCommand_ShouldPublish_PackageWasSentEvent were failing as they expecting SentAt to be after the fixture's TimeBeforeSending.  TimeBeforeSending was set to DateTime.UtcNow while the Package.SentAt was DateTime.Now.  This caused the tests to fail due to time zone discrepancies.
Fixes #62
=> Change Package.SentAt date to be DateTime.UtcNow

Sample/ECommerce/Carts/Carts.Api/Properties/launchSettings.json, Sample/ECommerce/Orders/Orders.Api/Properties/launchSettings.json, Sample/ECommerce/Payments/Payments.Api/Properties/launchSettings.json, Sample/ECommerce/Shipments/Shipments.Api/Properties/launchSettings.json
The launchUrls indicated the APIs should have different ports assigned.
However, since no applicationUrl was provided, they all ran on port 5000
(and 5001 for https)
Fix #67
=> Add applicationUrl to ECommerce Sample APIs

Core.WebApi/Swagger/MetadataOperationFilter.cs, Core.WebApi/Tracing/TracingHeadersExtensions.cs, Core.WebApi/Tracing/TracingMiddleware.cs, Core/Config.cs, Core/Tracing/TracingScope.cs
A follow-up PR to https://github.com/oskardudycz/EventSourcing.NetCore/pull/106
=> Added missing logic in TracingMiddleware to actually get correlation and causation ids from request headers

Core.Marten/Config.cs, Core/Tracing/TracingScope.cs
There was a redundant explicit registration leftover.
@cjjohansen, thank you (again) for catching that up 👍
=> Fixed Marten Append Scope registration

Core.EventStoreDB/Repository/EventStoreDBRepository.cs, Sample/EventStoreDB/ECommerce/Carts/Carts.Tests/Carts/ConfirmingCart/ConfirmCartTests.cs, Sample/EventStoreDB/ECommerce/Carts/Carts.Tests/Extensions/Reservations/CartExtensions.cs, Sample/EventStoreDB/ECommerce/Carts/Carts/ShoppingCarts/ShoppingCart.cs, Sample/EventStoreDB/Simple/ECommerce.Core/Commands/CommandHandler.cs
- for the case where no expected version was supplied, wrong version was used. ESDB has first revision set 0, and expects the revision of the stream before update. Fixed by sending an initial aggregate version at load,
- fixed setting the Cart aggregate version for Initialized event (should be 0 instead of 1),
- fixed dependencies scoping for the functions registration in Simple ESDB sample.
=> Fixed Optimistic Concurrency in ESDB Samples

Core/Events/StreamNameMapper.cs
All credits go to @bartelink and his PR https://github.com/EventStore/samples/pull/10.
=> Shift tenant to aggregateId part of streamId to properly handle EventStoreDB category projections

Workshops/IntroductionToEventSourcing/12-Projections/ProjectionsTests.cs, Workshops/IntroductionToEventSourcing/12-Projections/Tools/Database.cs, Workshops/IntroductionToEventSourcing/13-Projections.Idempotency/ProjectionsTests.cs, Workshops/IntroductionToEventSourcing/13-Projections.Idempotency/Tools/Database.cs, Workshops/IntroductionToEventSourcing/14-Projections.EventualConsistency/ProjectionsTests.cs, Workshops/IntroductionToEventSourcing/14-Projections.EventualConsistency/Tools/Database.cs
1. Fixed `Database.Store` method to do upsert instead of add.
2. Added hint on how to register an event handler.
3. Fixed copy/paste issues in projections tests
=> Updates to projections tests in Introduction to Event Sourcing workshop

README.md
This small PR fixes the link to Kafka Web page.
=> Fix link to Kafka Web page

README.md
The current Elastic Search link returns a 404.
=> Fix broken Elastic Search link

Core/Events/External/IExternaEventProducer.cs
Brought back publishing externally only events marked as `IExternalEvent` interface that was accidentally removed in https://github.com/oskardudycz/EventSourcing.NetCore/pull/150/files#diff-7bcf4d5fec16e94d333719daa573e42b1826b946dcd21327672c3ca31d1e31f6L27
=> Brought back publishing externally only events marked as IExternalEvent interface

Sample/Helpdesk/Helpdesk.Api/Incidents/GetCustomerIncidentsSummary/IncidentSummary.cs
Fix for this issue: https://github.com/oskardudycz/EventSourcing.NetCore/issues/172
``
{
"Id": "6e369857-b645-4acf-8961-41b07c918de5",
"Closed": 0,
"Pending": 4,
"Resolved": 0,
"Acknowledged": 1
}
``
Now ``/incidents-summary`` API is working as it should
=> Fix for CustomerIncidentsSummaryGrouper Issue in Helpdesk sample

Core.EventStoreDB/Repository/Config.cs, Core.EventStoreDB/Repository/EventStoreDBRepository.cs, Core.EventStoreDB/Repository/EventStoreDBRepositoryWithTelemetryDecorator.cs, Core.Marten/Repository/Config.cs, Core.Marten/Repository/MartenRepository.cs, Core.Marten/Repository/MartenRepositoryWithTelemetryDecorator.cs, Core/Core.csproj
Refactored to make the logic more explicit instead of convoluted append with tracing.
=> Added wrapper for Marten repository instead of the internal logic for tracing

Sample/ECommerce/Carts/Carts.Api.Tests/ShoppingCarts/Confirming/ConfirmShoppingCartTests.cs, Sample/ECommerce/Carts/Carts.Tests/Builders/CartBuilder.cs, Sample/ECommerce/Carts/Carts.Tests/Carts/ConfirmingCart/ConfirmCartTests.cs, Sample/ECommerce/Carts/Carts/ShoppingCarts/ShoppingCart.cs
`OrderInitialized` event is created in the asynchronous process after a cart is confirmed. It has to have at least one product in it. 
The cart could be confirmed without any products what would cause order initialization to fail silently.
Call stack:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Count')
at Orders.Orders.InitializingOrder.OrderInitialized.Create(Guid orderId, Guid clientId, IReadOnlyList`1 productItems, Decimal totalPrice, DateTime initializedAt) in D:\dev\EventSourcing.NetCore\Orders\Orders\Orders\InitializingOrder\OrderInitialized.cs:line 25
at Orders.Orders.Order..ctor(Guid id, Guid clientId, IReadOnlyList`1 productItems, Decimal totalPrice) in D:\dev\EventSourcing.NetCore\Orders\Orders\Orders\Order.cs:line …
```
=> Problem with order initialization

Core.EventStoreDB/Config.cs, Core.EventStoreDB/Serialization/EventStoreDBSerializer.cs, Core.EventStoreDB/Subscriptions/EventStoreDBSubscriptionToAll.cs, Core/Config.cs, Core/Events/EventTypeMapper.cs, Sample/EventsVersioning/EventsVersioning.Tests/EventsVersioning.Tests.csproj, Sample/EventsVersioning/EventsVersioning.Tests/ExplicitSerialization/ExplicitSerializationTests.cs, Sample/EventsVersioning/EventsVersioning.Tests/ExplicitSerialization/ShoppingCart.cs
Made slight improvements to EventTypeMapper, allowing it to be injected by DI
=> Event Type Mapping improvements

Sample/EventsVersioning/ECommerce.V1/ECommerce.V1.csproj, Sample/EventsVersioning/EventsVersioning.Tests/EventsVersioning.Tests.csproj, Sample/EventsVersioning/EventsVersioning.Tests/SnapshotTesting/EventsSnapshotTests.ShoppingCartConfirmed_WithCompleteData_IsCompatible.verified.txt, Sample/EventsVersioning/EventsVersioning.Tests/SnapshotTesting/EventsSnapshotTests.ShoppingCartConfirmed_WithOnlyRequiredData_IsCompatible.verified.txt, Sample/EventsVersioning/EventsVersioning.Tests/SnapshotTesting/EventsSnapshotTests.cs, Sample/EventsVersioning/EventsVersioning.Tests/SnapshotTesting/PackageSnapshotTests.cs, Sample/EventsVersioning/EventsVersioning.Tests/SnapshotTesting/PackageSnapshotTests.my_assembly_has_no_public_api_changes.verified.txt
This helps detect breaking changes in the API and can be useful for event schema versioning. Used tools:
1. [Verify](https://github.com/VerifyTests/Verify)  by @simoncropp for Snapshot Testing.
2. [PublicApiGenerator](https://github.com/PublicApiGenerator/PublicApiGenerator) by @PublicApiGenerator team.
3. [NuGet Package Validation](https://devblogs.microsoft.com/dotnet/package-validation/) from Microsoft to compare the new NuGet version with the published one.
=> Added various ways of running compatibility tests

Core.EventStoreDB.Tests/Commands/EventStoreDBAsyncCommandBusTests.cs, Core.EventStoreDB/Config.cs, Core.EventStoreDB/Subscriptions/EventStoreDBSubscriptionToAll.cs, Core.Marten/ExternalProjections/MartenExternalProjection.cs, Core/Projections/IProjection.cs, Sample/EventStoreDB/ECommerce/Carts/Carts.Api/Program.cs, Sample/EventStoreDB/Simple/ECommerce.Api.Tests/ShoppingCartsApplicationFactory.cs, Sample/EventStoreDB/Simple/ECommerce.Api/Program.cs, Sample/EventStoreDB/Simple/ECommerce.Core/Projections/EntityFrameworkProjection.cs
I hope that'll finally solve those bloody flaky integration tests.
But even if not, then it's still needed to handle idempotency correctly.
Fixes #232
=> Fixed handling of the LastProcessedPosition handling in EntityFrameworkProjection
